# Generated by Django 4.1.7 on 2023-08-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayaAPP', '0002_rename_phone_number_donationcontact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
