# Generated by Django 4.1.7 on 2023-07-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaAPP', '0003_contact_donationcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='created_at',
            new_name='date',
        ),
    ]
