# Generated by Django 4.1.7 on 2023-07-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaAPP', '0004_rename_created_at_likepost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='donationcontact',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='date',
        ),
    ]
