# Generated by Django 4.1.7 on 2023-07-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayaAPP', '0005_rename_created_date_commentpost_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'News & Events'},
        ),
    ]
