# Generated by Django 4.1.7 on 2023-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_cover',
            field=models.ImageField(default='default_cover.PNG', upload_to='profile_cover'),
        ),
    ]
